name       : numix-frost-themes
version    : 1.9.4
release    : 1
source     :
    - http://ftp.mirrorservice.org/sites/repo.cinnarch.com/antergos/x86_64/numix-frost-themes-1.9.4-1-any.pkg.tar.xz : c942f0f8898680efc78d88f4709d2e707d97b2710aa13cd6d09243a3fd8f2f47
license    : GPL-3.0
summary    : Numis Frost GTK Themes
description: |
    Numix is a modern flat theme with a combination of light and dark elements.
builddeps  :
setup      : |
build      : |
install    : |
    mkdir -p $installdir/usr/share/themes/
    cp -R usr/share/themes/Numix-Frost $installdir/usr/share/themes/.
    cp -R usr/share/themes/Numix-Frost-Light $installdir/usr/share/themes/.
    chmod a+r -R $installdir/usr/share/themes
