name       : evopop-gtk-theme
version    : 0.27
release    : 8
source     :
    - https://github.com/solus-project/evopop-gtk-theme/releases/download/0.27/evopop-gtk-theme-0.27.tar.xz : 5ab3dc0a3e48e6e9f1558b54547dd63f5e7b69f28742b2d7ec48b71f164c1c99
license    : GPL-3.0
summary    : A simple, flat and bold Gtk theme for Solus & Budgie Desktop
description: |
    A simple, flat and bold Gtk theme for Solus & Budgie Desktop. Iris Dark was used as base.
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
